spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:com/metropolis/authorization/dal/persistence/*Mapper.xml"
  type-aliases-package: com.metropolis.authorization.dal.entitys